Save a copy in Drive of the given notebook and make changes.

Output for each of the questions is provided below each question. You need to produce the same output.

In [ ]:
import numpy as np

 1. Create a 4x6 matrix filled with all zeros.

In [ ]:
m1=np.zeros((4,6))

2. Create a 5x5 matrix filled with all ones.

In [ ]:
m2=np.ones((5,5))

3.Create a matrix of (4,5) filled with 4.

In [ ]:
m3=np.full((4,5),4)

For questions 4-13, consider the matrix

a=[[1,2,3],[1,4,5],[8,4,2]]


4. Write a code to get print the shape of the given matrix.




In [ ]:
a=np.array([[1,2,3],[1,4,5],[8,4,2]])
a.shape

(3, 3)

5.Write the code to print number of elements in a.

In [ ]:
a.size

9

6. Print the 2nd row,1st column and element at (1,2) of a.

In [ ]:
print(a[2, :])
print(a[:,1])
print(a[1,2])

[8 4 2]
[2 4 4]
5


7. Change the element at (2,1) to 5.

In [ ]:
a[2,1]=5
print(a)

[[1 2 3]
 [1 4 5]
 [8 5 2]]


8. Print the first and the last element of the first row using stepsize approach.

In [ ]:
print(a[0, 0:-1:2])

[1]


9. Print the maximum and minimum values of a.

In [ ]:
print(np.max(a))
print(np.min(a))

8
1


10. Print row-wise maximum values and their indicies of a.

In [ ]:
print(np.max(a, axis=1))
print(np.argmax(a,axis=1))


[3 5 8]
[2 2 0]


11. Divide all the elements of a by 4.

In [ ]:
print(a/4)

[[0.25 0.5  0.75]
 [0.25 1.   1.25]
 [2.   1.25 0.5 ]]


12. Sort a along the second axis.

In [ ]:
np.sort(a,axis=1)

array([[1, 2, 3],
       [1, 4, 5],
       [2, 5, 8]])

13. Print the indices that would sort a along the second axis.

In [ ]:
np.argsort(a,axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

14. Create an identity matrix of size 6x6.

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

15. Let b=[1,4,3,2,6,8,5,4,2,0], split b into 3 arrays each of 3,4,3 elements.

In [ ]:
 b=np.array([1,4,3,2,6,8,5,4,2,0])
 np.array_split(b,[3,7])

[array([1, 4, 3]), array([2, 6, 8, 5]), array([4, 2, 0])]

16.Create a 1-D array of 40 evenly spaced elements between 0. and 1., inclusive.

In [ ]:
np.random.rand(1,40)

array([[0.93806657, 0.42220264, 0.73175216, 0.0397941 , 0.58230664,
        0.31783368, 0.72763219, 0.40465804, 0.72723194, 0.52730212,
        0.97708825, 0.15771863, 0.62778914, 0.72862137, 0.5209109 ,
        0.09484006, 0.21885743, 0.66948035, 0.18058749, 0.70941727,
        0.78491738, 0.47422281, 0.7266873 , 0.45444943, 0.35832603,
        0.24210022, 0.01614671, 0.67774895, 0.1516595 , 0.82906595,
        0.25115382, 0.67902729, 0.29953822, 0.98701222, 0.25109247,
        0.92905326, 0.01095065, 0.06269466, 0.07481577, 0.68337959]])

17. Mutliply given arrays element-wise.

a=[[4,7,2],[1,3,9]]

b=[[1,5,0],[2,7,5]]

In [ ]:
a=np.array([[4,7,2],[1,3,9]])

b=np.array([[1,5,0],[2,7,5]])
a*b

array([[ 4, 35,  0],
       [ 2, 21, 45]])

18. Create a 3x2 array with random values from 0 to 1.

In [ ]:
np.random.rand(3,2)

array([[0.75017742, 0.6684724 ],
       [0.6467045 , 0.01639114],
       [0.06183701, 0.43267008]])